<a href="https://colab.research.google.com/github/YuliannaG/DataScience7-8/blob/main/HW7%2C8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# HW7

Завдання 1


In [84]:
from sklearn.datasets import load_wine, load_iris
from sklearn.model_selection import train_test_split

import numpy as np
import matplotlib.pyplot as plt

from sklearn import linear_model

wine_dataset = load_wine(as_frame=True)
raw_X, y = load_wine(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, shuffle=True, random_state=0)

model = linear_model.LogisticRegression(penalty = 'none', fit_intercept = False, max_iter=5000)
model.fit(X_train, y_train)

LogisticRegression(fit_intercept=False, max_iter=5000, penalty='none')

In [49]:
model.coef_

array([[-0.07388718, -0.32178372, -0.17912748, -0.02566792, -1.03186069,
        -0.77294213,  0.01105083, -0.02585575,  0.54961538, -0.70073448],
       [ 0.08427797,  0.33814663,  0.54268508, -0.26342233,  3.12686006,
         1.18121937,  0.01868676, -0.22830149, -0.27347932,  0.36116254],
       [-0.01039079, -0.01636291, -0.3635576 ,  0.28909025, -2.09499937,
        -0.40827724, -0.02973759,  0.25415723, -0.27613606,  0.33957194]])

In [81]:
model.score(X_train, y_train)

0.83125

In [82]:
model.score(X_test, y_test)

0.7777777777777778

0.9 split = 1 and 0.68
0.7 split = 0.84 and 0.79
0.6 split = 0.87 and 0.82
0.5 split = 0.86 and 0.78
0.2 and 0.3 split = 0.82 and 0.83

best - around 0.3 and 0.6
optimal by resources - 0.3

Завдання 2

In [108]:
iris_dataset = load_iris(as_frame=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, shuffle=True, random_state=0)
clasifier = linear_model.LogisticRegression(random_state=0,max_iter = 5000)
clasifier.fit(X_train, y_train)

LogisticRegression(max_iter=5000, random_state=0)

In [101]:
clasifier.predict(X_test[:10, :])

array([0, 2, 1, 0, 2, 1, 0, 1, 1, 1])

In [105]:
y_test[:10]

array([0, 2, 1, 0, 1, 1, 0, 2, 1, 1])

In [107]:
clasifier.score(X_test, y_test)

0.8333333333333334

Завдання 3

In [11]:
from sklearn.datasets import load_diabetes
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import recall_score, precision_score
from sklearn.model_selection import train_test_split
from sklearn import linear_model


diabetes_dataset = load_diabetes(as_frame=True)
X,y = load_diabetes(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=0)
regr = linear_model.LinearRegression()
regr.fit(X_train, y_train)

LinearRegression()

In [14]:
y_pred = regr.predict(X_test)
y_pred.shape

(89,)

In [20]:
y_pred

array([238.47145247, 248.93170646, 164.05404165, 120.30794355,
       187.42422054, 259.04865002, 113.55556372, 188.07597044,
       149.49663441, 236.01099949, 172.24629506, 178.88073764,
       109.15751983,  92.13508975, 243.33042043,  87.356971  ,
       155.72606406,  66.99073989, 100.42610442, 218.09422877,
       196.66287912, 161.29832968, 161.70779605, 156.52520454,
       197.88796516, 167.57984206, 120.74478913,  84.83879727,
       192.03728687, 160.60687024, 175.17178362,  84.22833237,
       145.7995542 , 145.97333493, 140.96488953, 197.00421108,
       165.94322494, 190.65906468, 128.22520508, 206.41941223,
        84.35851196, 164.0256504 , 144.1056776 , 184.68355549,
       177.80238966,  74.32855231, 143.3660286 , 138.67726085,
       120.81146113, 234.34252077, 161.94390244,  74.5455476 ,
       154.71905074, 156.78884927, 237.42227096, 174.23053048,
       190.88212635, 118.98373473, 132.20418974, 168.52674824,
       214.74245466, 171.42364091, 157.37409906, 108.86

In [15]:
y_test.shape

(89,)

In [21]:
y_test

array([321., 215., 127.,  64., 175., 275., 179., 232., 142.,  99., 252.,
       174., 129.,  74., 264.,  49.,  86.,  75., 101., 155., 170., 276.,
       110., 136.,  68., 128., 103.,  93., 191., 196., 217., 181., 168.,
       200., 219., 281., 151., 257.,  49., 198.,  96., 179.,  95., 198.,
       244.,  89., 214., 182.,  84., 270., 156., 138., 113., 131., 195.,
       171., 122.,  61., 230., 235.,  52., 121., 144., 107., 132., 302.,
        53., 317., 137.,  57.,  98., 170.,  88.,  90.,  67., 163., 104.,
       186., 180., 283., 141., 150.,  47., 297., 104.,  49., 103., 142.,
        59.])

In [18]:
recall_score(y_test, y_pred)

ValueError: ignored

In [19]:
precision_score(y_test, y_pred)

ValueError: ignored

In [7]:
# The coefficients
print("Coefficients: \n", regr.coef_)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred))
# The coefficient of determination: 1 is perfect prediction
print("Coefficient of determination: %.2f" % r2_score(y_test, y_pred))

Coefficients: 
 [  -6.92791214 -261.90320276  672.08752531  251.15776027  334.94666979
 -389.4469787  -468.47100766 -100.63001358  561.4986084   -29.06277576]
Mean squared error: 3185.85
Coefficient of determination: 0.44
