<a href="https://colab.research.google.com/github/YuliannaG/DataScience7-8/blob/main/HW7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# HW7

Завдання 1


In [ ]:
from sklearn.datasets import load_wine, load_iris
from sklearn.model_selection import train_test_split

import numpy as np
import matplotlib.pyplot as plt

from sklearn import linear_model

wine_dataset = load_wine(as_frame=True)
raw_X, y = load_wine(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(raw_X, y, test_size=0.2, shuffle=True, random_state=0)

model = linear_model.RidgeClassifier(fit_intercept = False, max_iter=5000)
model.fit(X_train, y_train)

RidgeClassifier(fit_intercept=False, max_iter=5000)

In [ ]:
model.coef_

array([[-0.24532321,  0.05173108,  0.28005745, -0.12331069,  0.01782176,
         0.22652047,  0.07812392,  0.0056122 ,  0.05788827,  0.05357167,
         0.01306804,  0.30565229,  0.00117238],
       [ 0.16034414, -0.16099233, -0.45286404,  0.11973131, -0.01490017,
        -0.26818876,  0.18729188, -0.06921194,  0.19746499, -0.21273894,
         0.17572174, -0.1118734 , -0.00063718],
       [ 0.01710476,  0.10695146,  0.18057947, -0.0071185 , -0.0021716 ,
         0.03791928, -0.2588867 ,  0.05209408, -0.24994358,  0.17126353,
        -0.20802251, -0.20076225, -0.00058153]])

In [ ]:
model.score(X_train, y_train)

0.9859154929577465

In [ ]:
model.score(X_test, y_test)

0.9166666666666666

0.9 split = 1 and 0.93
0.7 split = 0.98 and 0.92
0.6 split = 0.98 and 0.94
0.5 split = 0.97 and 0.94
0.2  = 0.98 and 0.91

best - around 0.6

Завдання 2

In [ ]:
iris_dataset = load_iris(as_frame=True)
raw_X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(raw_X, y, test_size=0.3, shuffle=True, random_state=0)
clasifier = linear_model.RidgeClassifier(random_state=0,max_iter = 5000)
clasifier.fit(X_train, y_train)

RidgeClassifier(max_iter=5000, random_state=0)

In [ ]:
clasifier.predict(X_test[:10, :])

array([2, 1, 0, 2, 0, 2, 0, 2, 1, 1])

In [ ]:
y_test[:10]

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1])

In [ ]:
clasifier.score(X_test, y_test)

0.7555555555555555

Завдання 3

In [ ]:
from sklearn.datasets import load_diabetes
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import recall_score, precision_score
from sklearn.model_selection import train_test_split
from sklearn import linear_model



diabetes_dataset = load_diabetes(as_frame=True)
X,y = load_diabetes(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=0)
regr = linear_model.LinearRegression()
regr.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred = regr.predict(X_test)
y_pred.shape

(89,)

In [ ]:
y_pred

array([238.47145247, 248.93170646, 164.05404165, 120.30794355,
       187.42422054, 259.04865002, 113.55556372, 188.07597044,
       149.49663441, 236.01099949, 172.24629506, 178.88073764,
       109.15751983,  92.13508975, 243.33042043,  87.356971  ,
       155.72606406,  66.99073989, 100.42610442, 218.09422877,
       196.66287912, 161.29832968, 161.70779605, 156.52520454,
       197.88796516, 167.57984206, 120.74478913,  84.83879727,
       192.03728687, 160.60687024, 175.17178362,  84.22833237,
       145.7995542 , 145.97333493, 140.96488953, 197.00421108,
       165.94322494, 190.65906468, 128.22520508, 206.41941223,
        84.35851196, 164.0256504 , 144.1056776 , 184.68355549,
       177.80238966,  74.32855231, 143.3660286 , 138.67726085,
       120.81146113, 234.34252077, 161.94390244,  74.5455476 ,
       154.71905074, 156.78884927, 237.42227096, 174.23053048,
       190.88212635, 118.98373473, 132.20418974, 168.52674824,
       214.74245466, 171.42364091, 157.37409906, 108.86

In [ ]:
y_test.shape

(89,)

In [ ]:
y_test

array([321., 215., 127.,  64., 175., 275., 179., 232., 142.,  99., 252.,
       174., 129.,  74., 264.,  49.,  86.,  75., 101., 155., 170., 276.,
       110., 136.,  68., 128., 103.,  93., 191., 196., 217., 181., 168.,
       200., 219., 281., 151., 257.,  49., 198.,  96., 179.,  95., 198.,
       244.,  89., 214., 182.,  84., 270., 156., 138., 113., 131., 195.,
       171., 122.,  61., 230., 235.,  52., 121., 144., 107., 132., 302.,
        53., 317., 137.,  57.,  98., 170.,  88.,  90.,  67., 163., 104.,
       186., 180., 283., 141., 150.,  47., 297., 104.,  49., 103., 142.,
        59.])

In [ ]:
regr.score(X_test, y_test)

0.33222203269065176

In [ ]:
# The coefficients
print("Coefficients: \n", regr.coef_)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred))
# The coefficient of determination: 1 is perfect prediction
print("Coefficient of determination: %.2f" % r2_score(y_test, y_pred))

Coefficients: 
 [ -35.55683674 -243.1692265   562.75404632  305.47203008 -662.78772128
  324.27527477   24.78193291  170.33056502  731.67810787   43.02846824]
Mean squared error: 3424.32
Coefficient of determination: 0.33
